version: '3.7'
services:
  envoy:
    image: envoyproxy/envoy:v1.21-latest
    command: -c /etc/envoy/envoy.yaml --component-log-level wasm:debug    
    depends_on:
    - httpbin
    networks:
    - wasmtest
    ports:
    - "10000:10000"
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    - ./main.wasm:/etc/envoy/main.wasm

  httpbin:
    image: kennethreitz/httpbin:latest
    networks:
    - wasmtest
    ports:
    - "12345:80"

networks:
  wasmtest: {}
